---
- hosts: ci_deploy
  become: True
  tasks:
    - name: Install Java
      yum:
        name: java-1.8.0-openjdk
        state: "latest"
    - name: Download jar
    ansible.builtin.get_url:
      url: http://172.31.21.173:8081/repository/project-release/org/springframework/samples/spring-petclinic/4-2.4.5/spring-petclinic-4-2.4.5.jar
      dest: /home/cloud_user/
    - name: Deploy site
      ansible.builtin.shell:
        cmd: java jar spring-petclinic-4-2.4.5.jar
