---
- hosts: ci_deploy
  become: True
  tasks:
    - name: Install Java
      yum:
        name: java-1.8.0-openjdk
        state: "latest"
    - name: Download jar
      ansible.builtin.get_url:
        url: http://172.31.19.118:8081/repository/project-release/org/springframework/samples/spring-petclinic/9-2.4.5/spring-petclinic-9-2.4.5.jar
        dest: /home/ec2-user/
    - name: Deploy site
      ansible.builtin.shell:
        cmd: java jar /home/ec2-user/spring-petclinic-4-2.4.5.jar --server.port=8081
