---
- hosts: ci_deploy
  become: True
  tasks:
    - name: Install Java
      yum:
        name: java-1.8.0-openjdk
        state: "latest"
    - name: Download jar
      ansible.builtin.get_url:
        url: http://3.8.216.143:8081/repository/project-release/org/springframework/samples/spring-petclinic/4-2.4.5/spring-petclinic-4-2.4.5.jar
        dest: /home/cloud_user/
    - name: Deploy site
      ansible.builtin.shell:
        cmd: java jar /home/cloud_user/spring-petclinic-4-2.4.5.jar
